### ISSUE TITLE
Use of conduit or pipes

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/wormhole-client#15]
In the `receive` branch, we have this function `receiveRecords` that receives encrypted records from network and decrypts it into a ordered list of chunks of ByteStrings. This is picked up by another function and written into the disk. This is a nice separation of various concerns.

However, for a large file, this would blow up the memory usage until these bytestrings are written into the disk. Perhaps this presents a nice usecase to use streaming libraries like `Conduit`?

**Comment by vu3rdd** [comment]
In the `conduit` branch, there are a couple of WIP commits that implement a pipeline. There is a problem though: What we want is something like this:

source file -> chunk N -> sha256 pass through -> encrypt -> sink socket

At the moment, sha256 passthrough is implemented but not in the pipeline. We want overall result of the pipeline to be the sha256sum. But when we fuse conduits using the `(.|)` combinator, the result type need to be the same. We like sha256 passthrough and downstream to have the same result type. But I don't know how to do that yet.

@exarkun Any ideas how we can achieve this?

**Comment by vu3rdd** [comment]
Ok, I discovered Conduit's `fuseBoth`. Pushed a commit (https://github.com/LeastAuthority/wormhole-client/commit/fcfe81ef29da70c3961a57fe29caeedda8945dca) and it works now in a streaming fashion.

**Comment by exarkun** [comment]
Cool.  I'm excited to review this.  I've been aware of Conduit for a while but have not yet tried to investigate it.

**Comment by vu3rdd** [comment]
PR #17 and #19 implements this.
