### ISSUE TITLE
All uses of allocateTcpPort create a race condition and may result in EADDRINUSE failure

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/wormhole-client#18]
`allocateTcpPort` seems to be a helper for assigning a pseudo-random unused port number for a TCP listening socket.  The strategy taken is to create a socket, ask the OS TCP/IP stack to assign it a number, close the socket, and return the number it was assigned.

This fails when the OS TCP/IP stack or another application decides to bind another socket to that same assigned number in between when `allocateTcpPort` closes its probe socket and when the user-code calling `allocateTcpPort` gets around to binding its own socket to the number.

All uses of `allocateTcpPort` should be removed and the function itself deleted.

There are a number of possible replacements for this function.  Various options are outlined on [a Tahoe-LAFS ticket describing the same problem with that code base](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/2787).

**Comment by vu3rdd** [comment]
Thanks for the reference to the tahoe-lafs ticket. I already ran into the race issues with `allocateTcpPort` and had emailed Brian about it but didn't hear back from him. I will look at the suggested mitigation mechanisms from the Tahoe-LAFS trac ticket. Thanks.
