### ISSUE TITLE
Consider the transfer of this repository from LeastAuthority to magic-wormhole on GitHub

### ISSUE THREAD

**Issue by btlogy** [LeastAuthority/wormhole-client#83]
As requested by @meejah on Feb 23rd in an internal Least Authority channel:

> Does anyone have objections to me using GitHub's "move repository" feature to put this repository under the [magic-wormhole](https://github.com/magic-wormhole/) organization?

**Comment by btlogy** [comment]
Same as for LeastAuthority/haskell-magic-wormhole#71, decision has been made by Least Authority to hold off on transferring these repos until we determine the long-term plans for our product development work.

**Comment by meejah** [comment]
Least Authority has never used these codebases for any "product" (or used them at all), but, okay we'll fork them into the magic-wormhole organization instead I guess (unfortunately losing the issues and PRs in the process).

**Comment by btlogy** [comment]
> Least Authority has never used these codebases for any "product" (or used them at all), but, okay we'll fork them into the magic-wormhole organization instead I guess (unfortunately losing the issues and PRs in the process).

It should technically be possible to "copy" issues from one repository to another:

Example: https://gist.github.com/sheepeeh/07fbac85de50a39be1c48765d9116f12

This may require to create empty an repository first and then push all commits rather than use the fork feature of GitHub.
